version: '3.7'

services:
  todo-db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=todo
#  backend:
#      image: backend:1.0.0
#      ports:
#        - 8080:8080
